import { useCallback } from 'react';
import { motion } from 'framer-motion';
import {
    FileText,
    ArrowLeft,
    Brain,
    Lightbulb,
    Zap,
    Trophy,
    Target,
    Layout,
    CheckCircle2
} from 'lucide-react';
import {
    Radar,
    RadarChart,
    PolarGrid,
    PolarAngleAxis,
    ResponsiveContainer
} from 'recharts';
import { toast } from 'sonner';
// @ts-ignore
import html2pdf from 'html2pdf.js';

interface AnalysisResult {
    filename: string;
    candidate_name: string;
    analysis: {
        summary: string;
        skills: string;
        feedback: string;
        scores: {
            technical: number;
            soft_skills: number;
            impact: number;
            ats_rank: number;
            clarity: number;
        };
    };
}

interface DashboardPageProps {
    result: AnalysisResult;
    onReset: () => void;
}

export default function DashboardPage({ result, onReset }: DashboardPageProps) {
    const { filename, candidate_name, analysis } = result;

    const handleExportPDF = useCallback(async () => {
        toast.loading('Preparing your report...', { id: 'pdf-export' });

        // Build a clean, self-contained HTML string — NO Recharts, NO motion, NO glass
        const printHTML = `
            <div style="font-family: 'Inter', 'Helvetica', sans-serif; color: #101622; padding: 40px; width: 720px; background: white;">
                <div style="text-align: center; margin-bottom: 32px; border-bottom: 2px solid #135bec; padding-bottom: 24px;">
                    <h1 style="font-size: 28px; font-weight: 800; margin: 0 0 8px 0; color: #101622;">CV Analysis Report</h1>
                    <p style="font-size: 14px; color: #64748b; margin: 0;">File: ${filename} &nbsp;|&nbsp; Candidate: ${candidate_name || 'N/A'}</p>
                </div>

                <div style="margin-bottom: 28px;">
                    <h2 style="font-size: 18px; font-weight: 700; color: #135bec; margin: 0 0 12px 0; border-left: 4px solid #135bec; padding-left: 12px;">Executive Summary</h2>
                    <p style="font-size: 14px; line-height: 1.7; color: #334155; margin: 0; white-space: pre-wrap;">${analysis.summary}</p>
                </div>

                <div style="margin-bottom: 28px;">
                    <h2 style="font-size: 18px; font-weight: 700; color: #6366f1; margin: 0 0 12px 0; border-left: 4px solid #6366f1; padding-left: 12px;">Skills Identified</h2>
                    <div style="display: flex; flex-wrap: wrap; gap: 8px;">
                        ${analysis.skills.split('\n').map(s => s.trim()).filter(Boolean).map(s => s.replace(/^[-•*]\s*/, '')).map(skill =>
            `<span style="display: inline-block; padding: 6px 14px; background: #f1f5f9; border: 1px solid #e2e8f0; border-radius: 8px; font-size: 13px; font-weight: 600; color: #334155; margin-bottom: 4px; margin-right: 4px;">${skill}</span>`
        ).join('')}
                    </div>
                </div>

                <div style="margin-bottom: 28px;">
                    <h2 style="font-size: 18px; font-weight: 700; color: #f59e0b; margin: 0 0 12px 0; border-left: 4px solid #f59e0b; padding-left: 12px;">Feedback & Next Steps</h2>
                    <div style="display: flex; flex-direction: column; gap: 10px;">
                        ${analysis.feedback.split('\n').map(s => s.trim()).filter(Boolean).map(s => s.replace(/^[-•*\d.]\s*/, '')).map(line =>
            `<div style="display: flex; gap: 10px; align-items: flex-start; margin-bottom: 8px;">
                                <span style="color: #135bec; font-weight: 700; flex-shrink: 0;">▸</span>
                                <p style="font-size: 14px; line-height: 1.7; color: #334155; margin: 0;">${line}</p>
                            </div>`
        ).join('')}
                    </div>
                </div>

                <div style="border-top: 1px solid #e2e8f0; padding-top: 16px; text-align: center; margin-top: 40px;">
                    <p style="font-size: 11px; color: #94a3b8; margin: 0;">Generated by CV Reviewer &bull; ${new Date().toLocaleDateString()}</p>
                </div>
            </div>
        `;

        // Create a temporary container that is technically "visible" but hidden from the user
        const container = document.createElement('div');
        container.style.position = 'absolute';
        container.style.left = '0';
        container.style.top = '0';
        container.style.zIndex = '-9999';
        container.style.opacity = '0';
        container.style.pointerEvents = 'none';
        container.innerHTML = printHTML;
        document.body.appendChild(container);

        // Small delay to ensure the browser treats the DOM as 'painted'
        await new Promise(resolve => setTimeout(resolve, 300));

        const opt = {
            margin: [0.5, 0.5, 0.5, 0.5] as [number, number, number, number],
            filename: `CV_Report_${filename.replace(/\.[^/.]+$/, "")}.pdf`,
            image: { type: 'jpeg' as const, quality: 0.98 },
            html2canvas: {
                scale: 2,
                useCORS: true,
                logging: false,
                letterRendering: true
            },
            jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' as const },
            pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }
        };

        try {
            // @ts-ignore
            await html2pdf().set(opt).from(container).save();
            toast.success('Report exported successfully!', { id: 'pdf-export' });
        } catch (err) {
            console.error('PDF Export Error:', err);
            toast.error('Export failed. Please try again.', { id: 'pdf-export' });
        } finally {
            document.body.removeChild(container);
        }
    }, [filename, candidate_name, analysis]);

    const handleShareResults = async () => {
        const shareData = {
            title: `CV Analysis - ${candidate_name || filename}`,
            text: `Check out the AI-driven CV analysis for ${candidate_name || filename}. Summary: ${analysis.summary.substring(0, 100)}...`,
            url: window.location.href
        };

        if (navigator.share && navigator.canShare && navigator.canShare(shareData)) {
            try {
                await navigator.share(shareData);
                toast.success('Shared successfully!');
            } catch (err) {
                if ((err as Error).name !== 'AbortError') {
                    toast.error('Could not share. Copied to clipboard instead!');
                    navigator.clipboard.writeText(window.location.href);
                }
            }
        } else {
            navigator.clipboard.writeText(window.location.href);
            toast.success('Link copied to clipboard!');
        }
    };

    const skillLines = analysis.skills
        .split('\n')
        .map((s) => s.trim())
        .filter(Boolean)
        .map(s => s.replace(/^[-•*]\s*/, ''));

    const feedbackLines = analysis.feedback
        .split('\n')
        .map((s) => s.trim())
        .filter(Boolean)
        .map(s => s.replace(/^[-•*\d.]\s*/, ''));

    // Dynamic data for visualization based on analysis from backend
    const scores = analysis.scores || { technical: 80, soft_skills: 80, impact: 80, ats_rank: 80, clarity: 80 };

    const radarData = [
        { subject: 'Technical', A: scores.technical, fullMark: 100 },
        { subject: 'Soft Skills', A: scores.soft_skills, fullMark: 100 },
        { subject: 'Impact', A: scores.impact, fullMark: 100 },
        { subject: 'ATS Rank', A: scores.ats_rank, fullMark: 100 },
        { subject: 'Clarity', A: scores.clarity, fullMark: 100 },
    ];

    const statsData = [
        { name: 'Impact', value: scores.impact, color: '#135bec' },
        { name: 'Keywords', value: scores.ats_rank, color: '#6366f1' },
        { name: 'Formatting', value: scores.clarity, color: '#10b981' },
    ];

    // Calculate an average overall score
    const overallScore = Math.round(
        (scores.technical + scores.soft_skills + scores.impact + scores.ats_rank + scores.clarity) / 5
    );

    const containerVariants = {
        hidden: { opacity: 0 },
        show: {
            opacity: 1,
            transition: {
                staggerChildren: 0.1,
                delayChildren: 0.2
            }
        }
    };

    const itemVariants = {
        hidden: { opacity: 0, y: 20 },
        show: { opacity: 1, y: 0, transition: { duration: 0.6, ease: [0.22, 1, 0.36, 1] as any } }
    };

    return (
        <div className="pt-32 pb-24 px-6 md:px-12 bg-secondary/30 min-h-screen">
            <main className="max-w-7xl mx-auto">
                {/* Header Section */}
                <motion.div
                    initial={{ opacity: 0, y: -20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-12"
                >
                    <div className="space-y-4">
                        <button
                            onClick={onReset}
                            className="group flex items-center gap-2 text-sm font-bold text-muted-foreground hover:text-primary transition-colors mb-2"
                        >
                            <ArrowLeft className="w-4 h-4 transition-transform group-hover:-translate-x-1" />
                            Back to Upload
                        </button>
                        <h1 className="text-4xl md:text-5xl font-display font-bold text-foreground tracking-tight">
                            Analysis <span className="text-gradient">Report</span>
                        </h1>
                        <div className="flex items-center gap-3">
                            <div className="flex items-center gap-2 px-3 py-1 bg-white border border-border rounded-full shadow-sm">
                                <FileText className="w-4 h-4 text-primary" />
                                <span className="text-sm font-semibold">{filename}</span>
                            </div>
                            <div className="flex items-center gap-2 px-3 py-1 bg-primary/10 text-primary rounded-full">
                                <CheckCircle2 className="w-4 h-4" />
                                <span className="text-sm font-bold uppercase tracking-wider">Candidate: {candidate_name || "Extracted"}</span>
                            </div>
                        </div>
                    </div>

                    <div className="flex gap-4">
                        <button
                            onClick={handleExportPDF}
                            className="px-6 py-3 rounded-2xl bg-white border border-border font-bold hover:bg-secondary transition-all shadow-sm"
                        >
                            Export PDF
                        </button>
                        <button
                            onClick={handleShareResults}
                            className="px-6 py-3 rounded-2xl bg-foreground text-background font-bold shadow-xl hover:scale-105 active:scale-95 transition-all"
                        >
                            Share Results
                        </button>
                    </div>
                </motion.div>

                <motion.div
                    variants={containerVariants}
                    initial="hidden"
                    animate="show"
                    className="grid grid-cols-1 lg:grid-cols-12 gap-8"
                >
                    {/* Left Column: Visual Metrics */}
                    <motion.div variants={itemVariants} className="lg:col-span-4 space-y-8">
                        {/* Overall Score Card */}
                        <div className="glass bg-white p-8 rounded-[2.5rem] shadow-xl overflow-hidden relative">
                            <div className="absolute top-0 right-0 p-6 opacity-10">
                                <Trophy className="w-24 h-24" />
                            </div>
                            <div className="relative z-10 flex flex-col items-center text-center">
                                <div className="h-48 w-full mb-6">
                                    <ResponsiveContainer width="100%" height="100%">
                                        <RadarChart cx="50%" cy="50%" outerRadius="80%" data={radarData}>
                                            <PolarGrid stroke="#e2e8f0" />
                                            <PolarAngleAxis dataKey="subject" tick={{ fontSize: 10, fontWeight: 700, fill: '#64748b' }} />
                                            <Radar name="Score" dataKey="A" stroke="#135bec" fill="#135bec" fillOpacity={0.2} />
                                        </RadarChart>
                                    </ResponsiveContainer>
                                </div>
                                <div className="space-y-1">
                                    <span className="text-5xl font-display font-bold text-foreground">{overallScore}<span className="text-2xl text-primary">/100</span></span>
                                    <p className="text-sm font-bold text-muted-foreground uppercase tracking-widest italic">Industry Benchmark Score</p>
                                </div>
                            </div>
                        </div>

                        {/* Summary Card */}
                        <div className="glass bg-white p-8 rounded-[2.5rem] shadow-xl">
                            <div className="flex items-center gap-3 mb-6">
                                <div className="w-10 h-10 bg-primary/10 rounded-xl flex items-center justify-center text-primary">
                                    <Target className="w-5 h-5" />
                                </div>
                                <h3 className="text-xl font-display font-bold">Executive Summary</h3>
                            </div>
                            <p className="text-muted-foreground leading-relaxed text-lg italic">
                                "{analysis.summary}"
                            </p>
                        </div>
                    </motion.div>

                    {/* Right Column: Detailed Insights */}
                    <motion.div variants={itemVariants} className="lg:col-span-8 space-y-8">
                        {/* Metrics Grid */}
                        <div className="grid md:grid-cols-3 gap-6">
                            {statsData.map((stat, i) => (
                                <div key={i} className="glass bg-white p-6 rounded-3xl shadow-lg hover:shadow-2xl transition-all duration-500 hover:-translate-y-1">
                                    <p className="text-sm font-bold text-muted-foreground uppercase tracking-widest mb-4">{stat.name}</p>
                                    <div className="flex items-end justify-between">
                                        <span className="text-3xl font-display font-bold">{stat.value}%</span>
                                        <div className="w-16 h-1 rounded-full bg-border overflow-hidden mb-2">
                                            <div
                                                className="h-full rounded-full transition-all duration-1000"
                                                style={{ width: `${stat.value}%`, backgroundColor: stat.color }}
                                            />
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>

                        {/* Skills and Feedback Tabs Area */}
                        <div className="grid md:grid-cols-2 gap-8">
                            {/* Skills Section */}
                            <div className="glass bg-white p-8 rounded-[2.5rem] shadow-xl">
                                <div className="flex items-center gap-3 mb-8">
                                    <div className="w-10 h-10 bg-accent/10 rounded-xl flex items-center justify-center text-accent">
                                        <Brain className="w-5 h-5" />
                                    </div>
                                    <h3 className="text-xl font-display font-bold">Top Skills</h3>
                                </div>
                                <div className="flex flex-wrap gap-3">
                                    {skillLines.map((skill, i) => (
                                        <motion.span
                                            key={i}
                                            whileHover={{ scale: 1.05 }}
                                            className="px-4 py-2 bg-secondary/50 border border-border rounded-xl text-sm font-semibold hover:border-primary hover:text-primary transition-all cursor-default"
                                        >
                                            {skill}
                                        </motion.span>
                                    ))}
                                </div>
                            </div>

                            {/* Feedback Section */}
                            <div className="glass bg-white p-8 rounded-[2.5rem] shadow-xl">
                                <div className="flex items-center gap-3 mb-8">
                                    <div className="w-10 h-10 bg-amber-100 rounded-xl flex items-center justify-center text-amber-600">
                                        <Lightbulb className="w-5 h-5" />
                                    </div>
                                    <h3 className="text-xl font-display font-bold">Next Steps</h3>
                                </div>
                                <div className="space-y-6">
                                    {feedbackLines.map((line, i) => (
                                        <div key={i} className="flex gap-4 group">
                                            <div className="w-6 h-6 rounded-lg bg-secondary flex items-center justify-center text-primary group-hover:bg-primary group-hover:text-white transition-colors duration-300 transform group-hover:scale-110">
                                                <Zap className="w-3 h-3 fill-current" />
                                            </div>
                                            <p className="text-sm font-medium text-muted-foreground leading-relaxed group-hover:text-foreground transition-colors">
                                                {line}
                                            </p>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>

                        {/* Call to Action Premium */}
                        <motion.div
                            whileHover={{ y: -5 }}
                            className="bg-foreground rounded-[2.5rem] p-12 text-background relative overflow-hidden group shadow-2xl"
                        >
                            <div className="absolute top-0 right-0 p-12 opacity-10 group-hover:rotate-12 transition-transform duration-700">
                                <Layout className="w-48 h-48" />
                            </div>
                            <div className="relative z-10 max-w-lg">
                                <span className="inline-block px-3 py-1 bg-white/10 rounded-full text-[10px] font-bold uppercase tracking-widest mb-6 border border-white/20">
                                    Premium Service
                                </span>
                                <h3 className="text-3xl font-display font-bold mb-4">Want a professional 1-on-1 resume audit?</h3>
                                <p className="text-white/60 text-lg mb-8 leading-relaxed">
                                    Connect with career experts from Google, Meta, and Amazon to fine-tune your strategy.
                                </p>
                                <button className="px-8 py-4 bg-primary text-white font-bold rounded-2xl hover:bg-primary/90 transition-all shadow-xl shadow-primary/20">
                                    Book a Session
                                </button>
                            </div>
                        </motion.div>
                    </motion.div>
                </motion.div>
            </main>
        </div>
    );
}
